---
- name: Deploy local network monitoring
  hosts: localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/env python3

  tasks:
    - name: Deploy namespace
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: local-network-monitoring
            labels:
              stack: local-network-monitoring

            annotations:
              origin: https://github.com/OlGe404/local-network-monitor/blob/master/playbook.yaml

    - name: Deploy local-network-monitoring stack
      loop:
        - prometheus.yml
        - grafana.yml
        - blackbox-exporter.yml
        - speedtest-exporter.yml
      kubernetes.core.k8s:
       # state: absent
        namespace: local-network-monitoring
        template: "{{ item }}"

    - name: Trigger rolling update for pods to reload configs
      with_items:
        - { kind: StatefulSet, name: prometheus }
        - { kind: Deployment, name: grafana }

      kubernetes.core.k8s:
        definition:
          apiVersion: apps/v1
          kind: "{{ item.kind }}"
          metadata:
            name: "{{ item.name }}"
            namespace: local-network-monitoring
          spec:
            template:
              metadata:
                labels:
                  rolling-update: "{{ ansible_date_time.iso8601_basic_short }}"
