---
- name: Deploy local network monitoring
  hosts: localhost
  vars_files: vars.yaml
  tasks:
    - name: Deploy namespace
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ k8s_namespace }}"
            labels:
              stack: local-network-monitoring

    - name: Deploy local-network-monitoring components
      loop:
        - prometheus.yml
        - grafana.yml

      kubernetes.core.k8s:
        namespace: "{{ k8s_namespace }}"
        template: "{{ item }}"

    - name: Trigger rolling update for pods
      with_items:
        - { kind: StatefulSet, name: prometheus }

      kubernetes.core.k8s:
        definition:
          apiVersion: apps/v1
          kind: "{{ item.kind }}"
          metadata:
            name: "{{ item.name }}"
            namespace: "{{ k8s_namespace }}"
          spec:
            template:
              metadata:
                labels:
                  updated: "{{ ansible_date_time.iso8601_basic_short }}"
