---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-conf
  labels:
    app: prometheus
    stack: local-network-monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
            - localhost:9090

      - job_name: blackbox-exporter
        metrics_path: /probe
        params:
          module: [http_2xx]

        static_configs:
          - targets:
            - https://www.google.de

        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: blackbox-exporter:9115

      - job_name: speedtest-exporter
        metrics_path: /probe
        scrape_interval: 60m
        scrape_timeout: 30s
        params:
          script: [speedtest]

        static_configs:
          - targets:
              - speedtest-exporter:9469

      - job_name: speedtest-exporter-metrics
        metrics_path: /metrics
        static_configs:
          - targets:
              - speedtest-exporter:9469
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  labels:
    app: prometheus
    stack: local-network-monitoring
spec:
  volumeMode: Filesystem
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels: &labels
    app: prometheus
    stack: local-network-monitoring
spec:
  selector: *labels
  ports:
    - name: api
      port: 9090
      targetPort: api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  labels:
    app: prometheus
    stack: local-network-monitoring
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  labels: &labels
    app: prometheus
    stack: local-network-monitoring
spec:
  serviceName: prometheus
  serviceAccount: prometheus
  selector:
    matchLabels: *labels

  template:
    metadata:
      labels: *labels

    spec:
      volumes:
        - name: prometheus-data
          persistentVolumeClaim:
            claimName: prometheus-data

        - name: prometheus-conf
          configMap:
            name: prometheus-conf

      containers:
        - name: prometheus
          image: prom/prometheus:v2.44.0
          ports:
            - name: api
              containerPort: 9090

          volumeMounts:
            - name: prometheus-data
              mountPath: /prometheus

            - name: prometheus-conf
              mountPath: /etc/prometheus

          livenessProbe:
            httpGet:
              port: 9090
              path: /-/healthy

          readinessProbe:
            httpGet:
              port: 9090
              path: /-/ready
