---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-conf
  labels:
    app: prometheus
    stack: local-network-monitoring
data:
  prometheus.yml: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  labels:
    app: prometheus
    stack: local-network-monitoring
spec:
  volumeMode: Filesystem
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  labels:
    app: prometheus
    stack: local-network-monitoring
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  labels: &labels
    app: prometheus
    stack: local-network-monitoring
spec:
  serviceName: prometheus
  serviceAccount: prometheus
  selector:
    matchLabels: *labels

  template:
    metadata:
      labels: *labels

    spec:
      volumes:
        - name: prometheus-data
          persistentVolumeClaim:
            claimName: prometheus-data

        - name: prometheus-conf
          configMap:
            name: prometheus-conf

      containers:
        - name: prometheus
          image: prom/prometheus:v2.44.0
          ports:
            - name: webui
              containerPort: 9090

          volumeMounts:
            - name: prometheus-data
              mountPath: /prometheus

            - name: prometheus-conf
              mountPath: /etc/prometheus
